### ISSUE TITLE
Exercises page

### ISSUE THREAD

**Issue by Kellan-Anderson** [Kellan-Anderson/Gym-Workout-Tracker#14]
# Create exercises page

Feature: An page for a user to manage their exercises

## Epic Description

This feature will provide an interface for a user to add, read, edit & delete exercises that they will use in their workouts. This will also come with some added functionality for searching & sorting exercises

## List of Tasks (Complete in order)

- [ ] Task 1: [Create a way for the user to add an exercise](https://github.com/Kellan-Anderson/Gym-Workout-Tracker/issues/15)
- [ ] Task 2: [Make exercises list](https://github.com/Kellan-Anderson/Gym-Workout-Tracker/issues/17)
- [ ] Task 3: [Add options to exercises list](https://github.com/Kellan-Anderson/Gym-Workout-Tracker/issues/18)
- [ ] Task 4: [Add search bar to exercises page](https://github.com/Kellan-Anderson/Gym-Workout-Tracker/issues/19)
- [ ] Task 5: [Add sorting selector to exercises page](https://github.com/Kellan-Anderson/Gym-Workout-Tracker/issues/20)
