### ISSUE TITLE
Create home page

### ISSUE THREAD

**Issue by Kellan-Anderson** [Kellan-Anderson/Gym-Workout-Tracker#4]
# Create a home page for the app

Feature: Awesome Feature Title

## Epic Description

Need to create a home page for the app that displays a little information about the app's purpose and provides a way for a new user to sign in. If a user visits the home page and is already signed in, or if they sign in for the first time from the home page, they will be redirected to the dashboard page.

## List of Tasks (Complete in order)
- [x] Task 1: [Make home page & display info](https://github.com/Kellan-Anderson/Gym-Workout-Tracker/issues/5)
- [ ] Task 2: [Make a way for the user to sign in](https://github.com/Kellan-Anderson/Gym-Workout-Tracker/issues/6)
- [ ] Task 3: [Setup redirection on the home page](https://github.com/Kellan-Anderson/Gym-Workout-Tracker/issues/7)
